site_name: "EMT Documentation"
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
  features:
    - navigation.tabs: false
    - navigation.top: false
    - navigation.sections: true
    - search.suggest: true
    - search.highlight: true
  logo: assets/logo.png 
  favicon: assets/favicon.ico
  
extra_css:
  - assets/custom.css
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - awesome-pages
