sonar.projectKey=FairCompute_energy-monitoring-tool_0b11396c-f1bf-41be-910a-f93bbc56f045
sonar.host.url=https://sonarqube.workstation-home.com
sonar.sources=.
sonar.python.version=3.10, 3.11, 3.12
sonar.python.coverage.reportPaths=coverage.xml

# Exclude documentation, assets, and operational helper scripts
sonar.exclusions=assets/**/*,docs/**/*, examples/**/*, docs/assets/**/*, scripts/**/*, coverage-report*.xml
sonar.coverage.exclusions=examples/**/*,docs/**/*, assets/**/*, docs/assets/**/*, scripts/**/*, coverage-report*.xml
sonar.cpd.exclusions=examples/**/*,docs/**/*, assets/**/*, docs/assets/**/*, scripts/**/*, coverage-report*.xml


