name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_ENV_NAME: emt

jobs:
  linting:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Cached Conda Environment
        uses: ./.github/actions/create-cached-conda-environment
        with:
          conda-environment-name: ${{ env.PYTHON_ENV_NAME }}

      - name: Activate Conda Environment
        run: conda activate ${{ env.PYTHON_ENV_NAME }}
        shell: bash -li {0}

      - name: Run Black
        uses:  microsoft/action-python@0.7.3}
        with:
          black: true

      - name: Run Bandit
        uses:  microsoft/action-python@0.7.3
        with:
          bandit: true

      - name: Run Pylint
        uses:  microsoft/action-python@0.7.3}
        with:
          pylint: true

      - name: Run Pyright
        uses:  microsoft/action-python@0.7.3
        with:
          pyright: true

      - name: Run Flake8
        uses:  microsoft/action-python@0.7.3
        with:
          flake8: true

  testing:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Cached Conda Environment
        uses: ./.github/actions/create-cached-conda-environment
        with:
          conda-environment-name: ${{ env.PYTHON_ENV_NAME }}

      - name: Activate Conda Environment
        run: conda activate ${{ env.PYTHON_ENV_NAME }}
        shell: bash -li {0}

      - name: Run Pytest
        uses: microsoft/action-python@0.7.3
        with:
          testing: true