name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_ENV_NAME: emt

jobs:
  linting:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'pyproject.toml'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
          cache-key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}

      - run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install Dependencies
        run: conda env update --file environment.yml
        shell: bash -li {0}

      - name: Run Black
        uses: microsoft/action-python@0.7.3
        with:
          black: true

      - name: Run Bandit
        uses: microsoft/action-python@0.7.3
        with:
          bandit: true

      - name: Run Pylint
        uses: microsoft/action-python@0.7.3
        with:
          pylint: true

      - name: Run Pyright
        uses: microsoft/action-python@0.7.3
        with:
          pyright: true

      - name: Run Flake8
        uses: microsoft/action-python@0.7.3
        with:
          flake8: true

  testing:
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'pyproject.toml'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
          cache-key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}

      - run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Activate Conda Environment
        run: conda activate ${{ env.PYTHON_ENV_NAME }}
        shell: bash -li {0}

      - name: Run Pytest
        uses: microsoft/action-python@0.7.3
        with:
          testing: true